# Generated by Django 4.1.3 on 2022-11-24 13:02

import datetime
from django.db import migrations, models
import users.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(2022, 11, 24), validators=[users.validators.validators.validate_age], verbose_name='Date of brth'),
        ),
    ]
