# Generated by Django 4.1.3 on 2022-11-24 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата заполнения')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BB',
                'verbose_name_plural': 'BBs',
            },
        ),
    ]
